# Generated by Django 2.2 on 2019-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190418_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumb',
            field=models.ImageField(default='project.png', upload_to='project_thumbs'),
        ),
    ]
