# Generated by Django 2.2 on 2019-04-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190430_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ilustration',
            old_name='projectKey',
            new_name='project',
        ),
    ]
