# Generated by Django 2.2 on 2019-04-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectKey', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('teaser', models.TextField()),
            ],
        ),
    ]
