# Generated by Django 2.2 on 2019-04-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teaser',
            field=models.CharField(max_length=200),
        ),
    ]
