# Generated by Django 2.2 on 2019-04-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190418_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumb',
            field=models.ImageField(default='static/projects/project.png', upload_to='./static/projects'),
        ),
    ]
