# Generated by Django 2.2 on 2019-05-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20190430_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilustration',
            options={'ordering': ['caption']},
        ),
    ]
