# Generated by Django 2.2 on 2019-04-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='endYear',
            field=models.CharField(default='', max_length=4),
        ),
    ]
