# Generated by Django 2.2 on 2019-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('startYear', models.CharField(max_length=4)),
                ('endYear', models.CharField(max_length=4)),
                ('description', models.TextField()),
            ],
        ),
    ]
