# Generated by Django 2.2 on 2019-04-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='companyURL',
            field=models.CharField(default='fixLater', max_length=200),
            preserve_default=False,
        ),
    ]
